// Generated by AI under BqRetialis Architectural Specifications

#ifndef DESKTOP_H
#define DESKTOP_H

#include "../../BqSDK/bq_sdk.h"

enum DesktopLimit : UInt32
{
    DESKTOP_CURSOR_WIDTH  = 12,
    DESKTOP_CURSOR_HEIGHT = 16,
    DESKTOP_BG_COLOR      = 0x001E4D8C,
    DESKTOP_WHITE_COLOR   = 0x00FFFFFF,
    DESKTOP_BLACK_COLOR   = 0x00000000
};

typedef struct GopDisplayInfo
{
    UInt64 framebuffer_address;
    UInt32 width;
    UInt32 height;
    UInt32 pitch;
    UInt32 bpp;
} GopDisplayInfo;

typedef struct Ps2MouseState
{
    Int32  delta_x;
    Int32  delta_y;
    UInt32 buttons;
} Ps2MouseState;

typedef struct DesktopState
{
    UInt64           framebuffer_address;
    volatile UInt32* framebuffer;
    UInt32           width;
    UInt32           height;
    UInt32           pitch;
    Int32            cursor_x;
    Int32            cursor_y;
    Int32            prev_cursor_x;
    Int32            prev_cursor_y;
    UInt32           cursor_backup[DESKTOP_CURSOR_HEIGHT][DESKTOP_CURSOR_WIDTH];
} DesktopState;

void DesktopDrawCursor(DesktopState* state);
void DesktopRestoreCursor(DesktopState* state);
void DesktopFillBackground(DesktopState* state);
void _start(void);

#endif
