// Generated by AI under BqRetialis Architectural Specifications

#include "desktop.h"

static DesktopState s_desktop_state;

static const UInt8 s_cursor_mask[DESKTOP_CURSOR_HEIGHT][DESKTOP_CURSOR_WIDTH] =
{
    { 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 2, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0 },
    { 2, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0 },
    { 2, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0 },
    { 2, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0 },
    { 2, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0 },
    { 2, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0 },
    { 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0 },
    { 2, 1, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0 },
    { 2, 1, 2, 0, 2, 1, 2, 0, 0, 0, 0, 0 },
    { 2, 2, 0, 0, 2, 1, 2, 0, 0, 0, 0, 0 },
    { 2, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 0 },
    { 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0 }
};

void DesktopDrawCursor(DesktopState* state)
{
    if (state == NULL || state->framebuffer == NULL)
    {
        return;
    }

    Int32 cx = state->cursor_x;
    Int32 cy = state->cursor_y;

    for (UInt32 row = 0; row < DESKTOP_CURSOR_HEIGHT; row++)
    {
        for (UInt32 col = 0; col < DESKTOP_CURSOR_WIDTH; col++)
        {
            Int32 px = cx + (Int32)col;
            Int32 py = cy + (Int32)row;

            if (px >= 0 && px < (Int32)state->width && py >= 0 && py < (Int32)state->height)
            {
                UInt64 offset = ((UInt64)py * (UInt64)state->pitch) + (UInt64)px;
                state->cursor_backup[row][col] = state->framebuffer[offset];

                UInt8 pixel_val = s_cursor_mask[row][col];
                if (pixel_val == 1)
                {
                    state->framebuffer[offset] = DESKTOP_WHITE_COLOR;
                }
                else if (pixel_val == 2)
                {
                    state->framebuffer[offset] = DESKTOP_BLACK_COLOR;
                }
            }
        }
    }
}

void DesktopRestoreCursor(DesktopState* state)
{
    if (state == NULL || state->framebuffer == NULL)
    {
        return;
    }

    Int32 cx = state->cursor_x;
    Int32 cy = state->cursor_y;

    for (UInt32 row = 0; row < DESKTOP_CURSOR_HEIGHT; row++)
    {
        for (UInt32 col = 0; col < DESKTOP_CURSOR_WIDTH; col++)
        {
            Int32 px = cx + (Int32)col;
            Int32 py = cy + (Int32)row;

            if (px >= 0 && px < (Int32)state->width && py >= 0 && py < (Int32)state->height)
            {
                if (s_cursor_mask[row][col] != 0)
                {
                    UInt64 offset = ((UInt64)py * (UInt64)state->pitch) + (UInt64)px;
                    state->framebuffer[offset] = state->cursor_backup[row][col];
                }
            }
        }
    }
}

void DesktopFillBackground(DesktopState* state)
{
    if (state == NULL || state->framebuffer == NULL)
    {
        return;
    }

    for (UInt32 y = 0; y < state->height; y++)
    {
        for (UInt32 x = 0; x < state->width; x++)
        {
            state->framebuffer[((UInt64)y * (UInt64)state->pitch) + (UInt64)x] = DESKTOP_BG_COLOR;
        }
    }
}

void _start(void)
{
    UInt8* raw = (UInt8*)&s_desktop_state;
    for (UInt64 i = 0; i < sizeof(DesktopState); i++)
    {
        raw[i] = 0;
    }

    GopDisplayInfo display_info;
    display_info.framebuffer_address = 0;
    display_info.width  = 0;
    display_info.height = 0;
    display_info.pitch  = 0;
    display_info.bpp    = 0;

    for (;;)
    {
        UInt32 display_node = 0;
        if (BqResolvePath("\\Devices\\Display\\0", &display_node) == BQ_STATUS_SUCCESS && display_node != 0)
        {
            UInt64 bytes_read = 0;
            if (BqReadNodeBuffer(display_node, &display_info, sizeof(display_info), &bytes_read) == BQ_STATUS_SUCCESS &&
                display_info.width > 0 && display_info.height > 0)
            {
                break;
            }
        }

        BkFramebuffer fb;
        if (BqGetFramebuffer(&fb) == BQ_STATUS_SUCCESS && fb.width > 0 && fb.height > 0)
        {
            display_info.framebuffer_address = fb.physical_base;
            display_info.width  = fb.width;
            display_info.height = fb.height;
            display_info.pitch  = fb.pitch;
            display_info.bpp    = fb.bpp;
            break;
        }

        BqYield();
    }

    UInt32 pitch_pixels = (display_info.pitch >= (display_info.width * 4U))
                            ? (display_info.pitch / 4U)
                            : display_info.pitch;

    s_desktop_state.framebuffer_address = display_info.framebuffer_address;
    s_desktop_state.width               = display_info.width;
    s_desktop_state.height              = display_info.height;
    s_desktop_state.pitch               = pitch_pixels;

    UInt64 fb_size    = (UInt64)pitch_pixels * (UInt64)display_info.height * sizeof(UInt32);
    UInt64 page_count = (fb_size + 4095ULL) / 4096ULL;
    UInt64 fb_virt    = 0x0000600000000000ULL;
    UInt64 map_flags  = 7ULL;

    BqStatus map_status = BqMapVirtualRegion(fb_virt, display_info.framebuffer_address, page_count, map_flags);
    if (map_status == BQ_STATUS_SUCCESS)
    {
        s_desktop_state.framebuffer = (volatile UInt32*)fb_virt;
    }
    else
    {
        s_desktop_state.framebuffer = (volatile UInt32*)display_info.framebuffer_address;
    }

    DesktopFillBackground(&s_desktop_state);

    s_desktop_state.cursor_x      = (Int32)(s_desktop_state.width / 2);
    s_desktop_state.cursor_y      = (Int32)(s_desktop_state.height / 2);
    s_desktop_state.prev_cursor_x = s_desktop_state.cursor_x;
    s_desktop_state.prev_cursor_y = s_desktop_state.cursor_y;

    DesktopDrawCursor(&s_desktop_state);

    UInt32 mouse_node = 0;
    BqResolvePath("\\Devices\\Mouse\\0", &mouse_node);

    for (;;)
    {
        if (mouse_node == 0)
        {
            BqResolvePath("\\Devices\\Mouse\\0", &mouse_node);
        }

        if (mouse_node != 0)
        {
            Ps2MouseState mouse_state;
            UInt64 bytes_read = 0;

            if (BqReadNodeBuffer(mouse_node, &mouse_state, sizeof(mouse_state), &bytes_read) == BQ_STATUS_SUCCESS)
            {
                if (mouse_state.delta_x != 0 || mouse_state.delta_y != 0)
                {
                    Int32 new_x = s_desktop_state.cursor_x + mouse_state.delta_x;
                    Int32 new_y = s_desktop_state.cursor_y - mouse_state.delta_y;

                    if (new_x < 0)
                    {
                        new_x = 0;
                    }
                    if (new_x >= (Int32)s_desktop_state.width)
                    {
                        new_x = (Int32)s_desktop_state.width - 1;
                    }

                    if (new_y < 0)
                    {
                        new_y = 0;
                    }
                    if (new_y >= (Int32)s_desktop_state.height)
                    {
                        new_y = (Int32)s_desktop_state.height - 1;
                    }

                    if (new_x != s_desktop_state.cursor_x || new_y != s_desktop_state.cursor_y)
                    {
                        DesktopRestoreCursor(&s_desktop_state);

                        s_desktop_state.prev_cursor_x = s_desktop_state.cursor_x;
                        s_desktop_state.prev_cursor_y = s_desktop_state.cursor_y;
                        s_desktop_state.cursor_x      = new_x;
                        s_desktop_state.cursor_y      = new_y;

                        DesktopDrawCursor(&s_desktop_state);
                    }

                    mouse_state.delta_x = 0;
                    mouse_state.delta_y = 0;
                    BqWriteNodeBuffer(mouse_node, &mouse_state, sizeof(mouse_state));
                }
            }
        }

        BqYield();
    }
}
