// Generated by AI under BqRetialis Architectural Specifications

#include "ps2_mouse.h"

#define PS2_PORT_DATA                  0x60
#define PS2_PORT_STATUS                0x64
#define PS2_PORT_COMMAND               0x64

#define PS2_STATUS_OUTPUT_BUFFER_FULL  0x01
#define PS2_STATUS_INPUT_BUFFER_FULL   0x02
#define PS2_STATUS_MOUSE_DATA          0x20

#define PS2_CMD_ENABLE_AUX             0xA8
#define PS2_CMD_WRITE_AUX              0xD4

#define MOUSE_CMD_ENABLE_DATA_REPORT   0xF4

static void Ps2WaitInputEmpty(void)
{
    for (UInt32 i = 0; i < 10000; i++)
    {
        UInt8 status = 0;
        if (BqIoRead8(PS2_PORT_STATUS, &status) == BQ_STATUS_SUCCESS)
        {
            if ((status & PS2_STATUS_INPUT_BUFFER_FULL) == 0)
            {
                break;
            }
        }
    }
}

static void Ps2WaitOutputFull(void)
{
    for (UInt32 i = 0; i < 10000; i++)
    {
        UInt8 status = 0;
        if (BqIoRead8(PS2_PORT_STATUS, &status) == BQ_STATUS_SUCCESS)
        {
            if ((status & PS2_STATUS_OUTPUT_BUFFER_FULL) != 0)
            {
                break;
            }
        }
    }
}

static void Ps2MouseInit(void)
{
    Ps2WaitInputEmpty();
    BqIoWrite8(PS2_PORT_COMMAND, PS2_CMD_ENABLE_AUX);

    Ps2WaitInputEmpty();
    BqIoWrite8(PS2_PORT_COMMAND, PS2_CMD_WRITE_AUX);

    Ps2WaitInputEmpty();
    BqIoWrite8(PS2_PORT_DATA, MOUSE_CMD_ENABLE_DATA_REPORT);

    Ps2WaitOutputFull();
    UInt8 ack = 0;
    BqIoRead8(PS2_PORT_DATA, &ack);
    (void)ack;
}

void _start(void)
{
    Ps2MouseInit();

    UInt32 parent_id = 0;
    while (BqResolvePath("\\Devices\\Mouse", &parent_id) != BQ_STATUS_SUCCESS || parent_id == 0)
    {
        BqYield();
    }

    UInt32 node_id = 0;
    BqStatus status = BqCreateNode(parent_id, "0", FS_NODE_TYPE_DEVICE, FS_NODE_FLAG_READ | FS_NODE_FLAG_WRITE, &node_id);
    if (status != BQ_STATUS_SUCCESS)
    {
        while (BqResolvePath("\\Devices\\Mouse\\0", &node_id) != BQ_STATUS_SUCCESS || node_id == 0)
        {
            BqYield();
        }
    }

    Ps2MouseState mouse_state;
    mouse_state.delta_x = 0;
    mouse_state.delta_y = 0;
    mouse_state.buttons = 0;
    BqWriteNodeBuffer(node_id, &mouse_state, sizeof(mouse_state));

    UInt8 packet[3];
    UInt32 packet_byte_index = 0;

    for (;;)
    {
        UInt8 port_status = 0;
        while (BqIoRead8(PS2_PORT_STATUS, &port_status) == BQ_STATUS_SUCCESS &&
                (port_status & PS2_STATUS_OUTPUT_BUFFER_FULL) != 0 &&
                (port_status & PS2_STATUS_MOUSE_DATA) != 0)
        {
            UInt8 data_byte = 0;
            if (BqIoRead8(PS2_PORT_DATA, &data_byte) == BQ_STATUS_SUCCESS)
            {
                if (packet_byte_index == 0 && (data_byte & 0x08) == 0)
                {
                    continue;
                }

                packet[packet_byte_index++] = data_byte;

                if (packet_byte_index == 3)
                {
                    packet_byte_index = 0;

                    UInt8 flags = packet[0];
                    UInt8 raw_x = packet[1];
                    UInt8 raw_y = packet[2];

                    Int32 dx = (Int32)raw_x;
                    if ((flags & 0x10) != 0)
                    {
                        dx |= (Int32)0xFFFFFF00;
                    }

                    Int32 dy = (Int32)raw_y;
                    if ((flags & 0x20) != 0)
                    {
                        dy |= (Int32)0xFFFFFF00;
                    }

                    UInt64 bytes_read = 0;
                    BqReadNodeBuffer(node_id, &mouse_state, sizeof(mouse_state), &bytes_read);

                    mouse_state.delta_x += dx;
                    mouse_state.delta_y += dy;
                    mouse_state.buttons  = (UInt32)(flags & 0x07);

                    BqWriteNodeBuffer(node_id, &mouse_state, sizeof(mouse_state));
                }
            }
        }

        BqYield();
    }
}
