// Generated by AI under BqRetialis Architectural Specifications

#ifndef PS2_MOUSE_H
#define PS2_MOUSE_H

#include "../../BqSDK/bq_sdk.h"

typedef struct Ps2MouseState
{
    Int32  delta_x;
    Int32  delta_y;
    UInt32 buttons;
} Ps2MouseState;

#endif
