// Generated by AI under BqRetialis Architectural Specifications

#include "ps2_keyboard.h"

#define PS2_PORT_DATA                  0x60
#define PS2_PORT_STATUS                0x64

#define PS2_STATUS_OUTPUT_BUFFER_FULL  0x01
#define PS2_STATUS_MOUSE_DATA          0x20

void _start(void)
{
    UInt32 parent_id = 0;
    while (BqResolvePath("\\Devices\\Keyboard", &parent_id) != BQ_STATUS_SUCCESS || parent_id == 0)
    {
        BqYield();
    }

    UInt32 node_id = 0;
    BqStatus status = BqCreateNode(parent_id, "0", FS_NODE_TYPE_DEVICE, FS_NODE_FLAG_READ | FS_NODE_FLAG_WRITE, &node_id);
    if (status != BQ_STATUS_SUCCESS)
    {
        while (BqResolvePath("\\Devices\\Keyboard\\0", &node_id) != BQ_STATUS_SUCCESS || node_id == 0)
        {
            BqYield();
        }
    }

    Ps2KeyboardState current_state;
    current_state.scancode    = 0;
    current_state.is_pressed  = 0;
    current_state.reserved[0] = 0;
    current_state.reserved[1] = 0;
    BqWriteNodeBuffer(node_id, &current_state, sizeof(current_state));

    for (;;)
    {
        UInt8 port_status = 0;
        if (BqIoRead8(PS2_PORT_STATUS, &port_status) == BQ_STATUS_SUCCESS)
        {
            if ((port_status & PS2_STATUS_OUTPUT_BUFFER_FULL) != 0 &&
                (port_status & PS2_STATUS_MOUSE_DATA) == 0)
            {
                UInt8 scancode_byte = 0;
                if (BqIoRead8(PS2_PORT_DATA, &scancode_byte) == BQ_STATUS_SUCCESS)
                {
                    if ((scancode_byte & 0x80) != 0)
                    {
                        current_state.scancode   = scancode_byte & 0x7F;
                        current_state.is_pressed = 0;
                    }
                    else
                    {
                        current_state.scancode   = scancode_byte;
                        current_state.is_pressed = 1;
                    }

                    BqWriteNodeBuffer(node_id, &current_state, sizeof(current_state));
                }
            }
        }

        BqYield();
    }
}
