// Generated by AI under BqRetialis Architectural Specifications

#ifndef PS2_KEYBOARD_H
#define PS2_KEYBOARD_H

#include "../../BqSDK/bq_sdk.h"

typedef struct Ps2KeyboardState
{
    UInt8 scancode;
    UInt8 is_pressed;
    UInt8 reserved[2];
} Ps2KeyboardState;

#endif
