// Generated by AI under BqRetialis Architectural Specifications

#ifndef ATA_STORAGE_H
#define ATA_STORAGE_H

#include "../../BqSDK/bq_sdk.h"

enum AtaStorageCommand : UInt32
{
    ATA_STORAGE_CMD_NONE  = 0,
    ATA_STORAGE_CMD_READ  = 1,
    ATA_STORAGE_CMD_WRITE = 2
};

enum AtaStorageStatus : UInt32
{
    ATA_STORAGE_STATUS_IDLE    = 0,
    ATA_STORAGE_STATUS_PENDING = 1,
    ATA_STORAGE_STATUS_SUCCESS = 2,
    ATA_STORAGE_STATUS_ERROR   = 3
};

typedef struct AtaStoragePacket
{
    UInt32 command;
    UInt32 status;
    UInt64 lba;
    UInt32 sector_count;
    UInt8  data[512];
} AtaStoragePacket;

UInt8  AtaWaitBusy(void);
UInt8  AtaWaitDrq(void);
UInt32 AtaReadSector(UInt64 lba, UInt8* buffer);
UInt32 AtaWriteSector(UInt64 lba, const UInt8* buffer);
void   _start(void);

#endif
