// Generated by AI under BqRetialis Architectural Specifications

#include "ata_storage.h"

#define ATA_PORT_DATA         0x1F0
#define ATA_PORT_ERROR        0x1F1
#define ATA_PORT_SECTOR_COUNT 0x1F2
#define ATA_PORT_LBA_LOW      0x1F3
#define ATA_PORT_LBA_MID      0x1F4
#define ATA_PORT_LBA_HIGH     0x1F5
#define ATA_PORT_DRIVE_HEAD   0x1F6
#define ATA_PORT_STATUS       0x1F7
#define ATA_PORT_COMMAND      0x1F7

#define ATA_STATUS_ERR  0x01
#define ATA_STATUS_DRQ  0x08
#define ATA_STATUS_DF   0x20
#define ATA_STATUS_DRDY 0x40
#define ATA_STATUS_BSY  0x80

#define ATA_CMD_READ_SECTORS  0x20
#define ATA_CMD_WRITE_SECTORS 0x30

UInt8 AtaWaitBusy(void)
{
    for (UInt32 i = 0; i < 100000; i++)
    {
        UInt8 status = 0;
        if (BqIoRead8(ATA_PORT_STATUS, &status) == BQ_STATUS_SUCCESS)
        {
            if ((status & ATA_STATUS_BSY) == 0)
            {
                return status;
            }
        }
    }

    return 0xFF;
}

UInt8 AtaWaitDrq(void)
{
    for (UInt32 i = 0; i < 100000; i++)
    {
        UInt8 status = 0;
        if (BqIoRead8(ATA_PORT_STATUS, &status) == BQ_STATUS_SUCCESS)
        {
            if ((status & ATA_STATUS_BSY) == 0)
            {
                if ((status & (ATA_STATUS_ERR | ATA_STATUS_DF)) != 0)
                {
                    return 0;
                }

                if ((status & ATA_STATUS_DRQ) != 0)
                {
                    return 1;
                }
            }
        }
    }

    return 0;
}

UInt32 AtaReadSector(UInt64 lba, UInt8* buffer)
{
    if (buffer == NULL || lba > 0x0FFFFFFFULL)
    {
        return 0;
    }

    if (AtaWaitBusy() == 0xFF)
    {
        return 0;
    }

    BqIoWrite8(ATA_PORT_DRIVE_HEAD, (UInt8)(0xE0 | ((lba >> 24) & 0x0F)));
    BqIoWrite8(ATA_PORT_SECTOR_COUNT, 1);
    BqIoWrite8(ATA_PORT_LBA_LOW, (UInt8)(lba & 0xFF));
    BqIoWrite8(ATA_PORT_LBA_MID, (UInt8)((lba >> 8) & 0xFF));
    BqIoWrite8(ATA_PORT_LBA_HIGH, (UInt8)((lba >> 16) & 0xFF));
    BqIoWrite8(ATA_PORT_COMMAND, ATA_CMD_READ_SECTORS);

    if (AtaWaitDrq() == 0)
    {
        return 0;
    }

    UInt16* word_buf = (UInt16*)buffer;
    for (UInt32 i = 0; i < 256; i++)
    {
        UInt16 val = 0;
        BqIoRead16(ATA_PORT_DATA, &val);
        word_buf[i] = val;
    }

    return 1;
}

UInt32 AtaWriteSector(UInt64 lba, const UInt8* buffer)
{
    if (buffer == NULL || lba > 0x0FFFFFFFULL)
    {
        return 0;
    }

    if (AtaWaitBusy() == 0xFF)
    {
        return 0;
    }

    BqIoWrite8(ATA_PORT_DRIVE_HEAD, (UInt8)(0xE0 | ((lba >> 24) & 0x0F)));
    BqIoWrite8(ATA_PORT_SECTOR_COUNT, 1);
    BqIoWrite8(ATA_PORT_LBA_LOW, (UInt8)(lba & 0xFF));
    BqIoWrite8(ATA_PORT_LBA_MID, (UInt8)((lba >> 8) & 0xFF));
    BqIoWrite8(ATA_PORT_LBA_HIGH, (UInt8)((lba >> 16) & 0xFF));
    BqIoWrite8(ATA_PORT_COMMAND, ATA_CMD_WRITE_SECTORS);

    if (AtaWaitDrq() == 0)
    {
        return 0;
    }

    const UInt16* word_buf = (const UInt16*)buffer;
    for (UInt32 i = 0; i < 256; i++)
    {
        BqIoWrite16(ATA_PORT_DATA, word_buf[i]);
    }

    AtaWaitBusy();
    return 1;
}

void _start(void)
{
    UInt32 parent_id = 0;
    while (BqResolvePath("\\Devices\\Storage", &parent_id) != BQ_STATUS_SUCCESS || parent_id == 0)
    {
        BqYield();
    }

    UInt32 node_id = 0;
    BqStatus status = BqCreateNode(parent_id, "0", FS_NODE_TYPE_DEVICE, FS_NODE_FLAG_READ | FS_NODE_FLAG_WRITE, &node_id);
    if (status != BQ_STATUS_SUCCESS)
    {
        while (BqResolvePath("\\Devices\\Storage\\0", &node_id) != BQ_STATUS_SUCCESS || node_id == 0)
        {
            BqYield();
        }
    }

    AtaStoragePacket packet;
    UInt8* raw = (UInt8*)&packet;
    for (UInt64 i = 0; i < sizeof(AtaStoragePacket); i++)
    {
        raw[i] = 0;
    }

    if (AtaReadSector(0, packet.data) != 0)
    {
        packet.status = ATA_STORAGE_STATUS_SUCCESS;
    }
    else
    {
        packet.status = ATA_STORAGE_STATUS_IDLE;
    }

    packet.command      = ATA_STORAGE_CMD_NONE;
    packet.lba          = 0;
    packet.sector_count = 1;

    BqWriteNodeBuffer(node_id, &packet, sizeof(packet));

    for (;;)
    {
        UInt64 bytes_read = 0;
        if (BqReadNodeBuffer(node_id, &packet, sizeof(packet), &bytes_read) == BQ_STATUS_SUCCESS)
        {
            if (packet.status == ATA_STORAGE_STATUS_PENDING)
            {
                if (packet.command == ATA_STORAGE_CMD_READ)
                {
                    if (AtaReadSector(packet.lba, packet.data) != 0)
                    {
                        packet.status = ATA_STORAGE_STATUS_SUCCESS;
                    }
                    else
                    {
                        packet.status = ATA_STORAGE_STATUS_ERROR;
                    }

                    BqWriteNodeBuffer(node_id, &packet, sizeof(packet));
                }
                else if (packet.command == ATA_STORAGE_CMD_WRITE)
                {
                    if (AtaWriteSector(packet.lba, packet.data) != 0)
                    {
                        packet.status = ATA_STORAGE_STATUS_SUCCESS;
                    }
                    else
                    {
                        packet.status = ATA_STORAGE_STATUS_ERROR;
                    }

                    BqWriteNodeBuffer(node_id, &packet, sizeof(packet));
                }
            }
        }

        BqYield();
    }
}
