// Generated by AI under BqRetialis Architectural Specifications

#ifndef GOP_DISPLAY_H
#define GOP_DISPLAY_H

#include "../../BqSDK/bq_sdk.h"

typedef struct GopDisplayInfo
{
    UInt64 framebuffer_address;
    UInt32 width;
    UInt32 height;
    UInt32 pitch;
    UInt32 bpp;
} GopDisplayInfo;

#endif
