// Generated by AI under BqRetialis Architectural Specifications

#include "gop_display.h"

void _start(void)
{
    BkFramebuffer fb;
    BqStatus status = BqGetFramebuffer(&fb);
    while (status != BQ_STATUS_SUCCESS || fb.width == 0 || fb.height == 0)
    {
        BqYield();
        status = BqGetFramebuffer(&fb);
    }

    GopDisplayInfo info;
    info.framebuffer_address = fb.physical_base;
    info.width               = fb.width;
    info.height              = fb.height;
    info.pitch               = fb.pitch;
    info.bpp                 = fb.bpp;

    UInt32 parent_id = 0;
    while (BqResolvePath("\\Devices\\Display", &parent_id) != BQ_STATUS_SUCCESS || parent_id == 0)
    {
        BqYield();
    }

    UInt32 node_id = 0;
    status = BqCreateNode(parent_id, "0", FS_NODE_TYPE_DEVICE, FS_NODE_FLAG_READ | FS_NODE_FLAG_WRITE, &node_id);
    if (status != BQ_STATUS_SUCCESS)
    {
        while (BqResolvePath("\\Devices\\Display\\0", &node_id) != BQ_STATUS_SUCCESS || node_id == 0)
        {
            BqYield();
        }
    }

    BqWriteNodeBuffer(node_id, &info, sizeof(info));

    for (;;)
    {
        BqYield();
    }
}
