// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_VM_H
#define BQ_BOOT_VM_H

#include "bq_boot_types.h"

enum BqBootVmPageFlags: UInt64
{
    BQ_BOOT_VM_FLAG_PRESENT       = (1ULL << 0),
    BQ_BOOT_VM_FLAG_WRITABLE      = (1ULL << 1),
    BQ_BOOT_VM_FLAG_USER          = (1ULL << 2),
    BQ_BOOT_VM_FLAG_WRITE_THROUGH = (1ULL << 3),
    BQ_BOOT_VM_FLAG_CACHE_DISABLE = (1ULL << 4),
    BQ_BOOT_VM_FLAG_ACCESSED      = (1ULL << 5),
    BQ_BOOT_VM_FLAG_DIRTY         = (1ULL << 6),
    BQ_BOOT_VM_FLAG_HUGE_PAGE     = (1ULL << 7),
    BQ_BOOT_VM_FLAG_GLOBAL        = (1ULL << 8)
};

struct BqBootVmPageTable
{
    UInt64 entries[512];
}
__attribute__((aligned(4096)));

struct BqBootVmLedger
{
    UInt64 pml4_address;
    UInt64 stack_top;
};

#endif
