// Generated by AI under BqRetialis Architectural Specifications

#include "bq_boot_main.h"

static struct BqBootVmLedger s_vm_ledger;

BqBootStatus BqBootVmBuildPageTables(UInt64* pml4_address, EfiSystemTable* system_table, BqBootKernelLayout* kernel_layout, BqBootFramebuffer* framebuffer)
{
    if (pml4_address == NULL || system_table == NULL ||
        system_table->boot_services == NULL || kernel_layout == NULL)
    {
        return BQ_BOOT_STATUS_INVALID_PARAMETER;
    }

    UInt64 virt_offset        = kernel_layout->virtual_base & 0xFFFULL;
    UInt64 virt_base_aligned  = kernel_layout->virtual_base & ~0xFFFULL;
    UInt64 phys_base_aligned  = kernel_layout->physical_base & ~0xFFFULL;
    UInt64 size_aligned       = (kernel_layout->region_size + virt_offset + 0xFFFULL) & ~0xFFFULL;
    UInt64 total_kernel_pages = size_aligned / 4096ULL;
    if (total_kernel_pages == 0)
    {
        total_kernel_pages = 1ULL;
    }

    UInt64 offset_in_2mb = virt_base_aligned & 0x1FFFFFULL;
    UInt64 num_pt_kernel = (offset_in_2mb + size_aligned + 0x1FFFFFULL) / 0x200000ULL;
    if (num_pt_kernel < 2ULL)
    {
        num_pt_kernel = 2ULL;
    }

    UInt64 start_pml4_idx = (virt_base_aligned >> 39) & 0x1FFULL;
    UInt64 start_pdpt_idx = (virt_base_aligned >> 30) & 0x1FFULL;
    UInt64 start_pd_idx   = (virt_base_aligned >> 21) & 0x1FFULL;

    if (start_pd_idx + num_pt_kernel > 512ULL)
    {
        return BQ_BOOT_STATUS_UNSUPPORTED;
    }

    UInt64 extra_fb_pds = 0;
    if (framebuffer != NULL && framebuffer->region_size > 0)
    {
        UInt64 fb_gb_start = framebuffer->physical_base >> 30;
        UInt64 fb_gb_end   = (framebuffer->physical_base + framebuffer->region_size + 0x3FFFFFFFULL) >> 30;
        for (UInt64 gb = fb_gb_start; gb < fb_gb_end && gb < 512ULL; gb++)
        {
            if (gb >= 64ULL)
            {
                extra_fb_pds++;
            }
        }
    }

    UInt64 stack_pages = 4ULL;
    UInt64 total_pages = 1ULL + 1ULL + 64ULL + extra_fb_pds + 1ULL + 1ULL + num_pt_kernel + stack_pages;

    UInt64 tables_phys = 0xFFFFFFFFULL;
    UInt64 status = system_table->boot_services->allocate_pages(AllocateMaxAddress, EfiLoaderData, total_pages, &tables_phys);
    if (status != 0 || tables_phys == 0)
    {
        status = system_table->boot_services->allocate_pages(AllocateAnyPages, EfiLoaderData, total_pages, &tables_phys);
        if (status != 0 || tables_phys == 0)
        {
            return BQ_BOOT_STATUS_OUT_OF_RESOURCES;
        }
    }

    system_table->boot_services->set_mem((void*)tables_phys, total_pages * 4096ULL, 0);

    UInt64 current_page = 0;

    struct BqBootVmPageTable* pml4 = (struct BqBootVmPageTable*)(tables_phys + (current_page * 4096ULL));
    current_page += 1ULL;

    struct BqBootVmPageTable* pdpt_ident = (struct BqBootVmPageTable*)(tables_phys + (current_page * 4096ULL));
    current_page += 1ULL;

    UInt64 pd_ident_base = tables_phys + (current_page * 4096ULL);
    current_page += 64ULL;

    UInt64 fb_pd_base = tables_phys + (current_page * 4096ULL);
    current_page += extra_fb_pds;

    struct BqBootVmPageTable* pdpt_kernel = (struct BqBootVmPageTable*)(tables_phys + (current_page * 4096ULL));
    current_page += 1ULL;

    struct BqBootVmPageTable* pd_kernel = (struct BqBootVmPageTable*)(tables_phys + (current_page * 4096ULL));
    current_page += 1ULL;

    UInt64 pt_kernel_base = tables_phys + (current_page * 4096ULL);
    current_page += num_pt_kernel;

    UInt64 stack_top = tables_phys + (total_pages * 4096ULL);

    UInt64 table_flags = BQ_BOOT_VM_FLAG_PRESENT | BQ_BOOT_VM_FLAG_WRITABLE;
    UInt64 huge_flags  = BQ_BOOT_VM_FLAG_PRESENT | BQ_BOOT_VM_FLAG_WRITABLE | BQ_BOOT_VM_FLAG_HUGE_PAGE;

    pml4->entries[0]   = ((UInt64)pdpt_ident) | table_flags;
    pml4->entries[256] = ((UInt64)pdpt_ident) | table_flags;

    for (UInt64 p = 0; p < 64ULL; p++)
    {
        struct BqBootVmPageTable* pd = (struct BqBootVmPageTable*)(pd_ident_base + (p * 4096ULL));
        pdpt_ident->entries[p] = ((UInt64)pd) | table_flags;

        for (UInt64 e = 0; e < 512ULL; e++)
        {
            UInt64 phys = (p * 512ULL + e) * 0x200000ULL;
            pd->entries[e] = phys | huge_flags;
        }
    }

    if (extra_fb_pds > 0 && framebuffer != NULL)
    {
        UInt64 fb_gb_start = framebuffer->physical_base >> 30;
        UInt64 fb_gb_end   = (framebuffer->physical_base + framebuffer->region_size + 0x3FFFFFFFULL) >> 30;
        UInt64 fb_pd_idx   = 0;

        for (UInt64 gb = fb_gb_start; gb < fb_gb_end && gb < 512ULL; gb++)
        {
            if (gb >= 64ULL)
            {
                struct BqBootVmPageTable* pd_fb = (struct BqBootVmPageTable*)(fb_pd_base + (fb_pd_idx * 4096ULL));
                fb_pd_idx++;

                pdpt_ident->entries[gb] = ((UInt64)pd_fb) | table_flags;

                for (UInt64 e = 0; e < 512ULL; e++)
                {
                    UInt64 phys = (gb * 512ULL + e) * 0x200000ULL;
                    pd_fb->entries[e] = phys | huge_flags;
                }
            }
        }
    }

    pml4->entries[start_pml4_idx]        = ((UInt64)pdpt_kernel) | table_flags;
    pdpt_kernel->entries[start_pdpt_idx] = ((UInt64)pd_kernel) | table_flags;

    for (UInt64 t = 0; t < num_pt_kernel; t++)
    {
        struct BqBootVmPageTable* pt = (struct BqBootVmPageTable*)(pt_kernel_base + (t * 4096ULL));
        pd_kernel->entries[start_pd_idx + t] = ((UInt64)pt) | table_flags;
    }

    for (UInt64 i = 0; i < total_kernel_pages; i++)
    {
        UInt64 cur_virt = virt_base_aligned + (i * 4096ULL);
        UInt64 cur_phys = phys_base_aligned + (i * 4096ULL);

        UInt64 cur_pd_idx   = (cur_virt >> 21) & 0x1FFULL;
        UInt64 pt_array_idx = cur_pd_idx - start_pd_idx;
        UInt64 cur_pt_idx   = (cur_virt >> 12) & 0x1FFULL;

        struct BqBootVmPageTable* pt = (struct BqBootVmPageTable*)(pt_kernel_base + (pt_array_idx * 4096ULL));
        pt->entries[cur_pt_idx] = cur_phys | table_flags;
    }

    s_vm_ledger.pml4_address = tables_phys;
    s_vm_ledger.stack_top    = stack_top;

    *pml4_address = tables_phys;

    return BQ_BOOT_STATUS_SUCCESS;
}

BqBootStatus BqBootVmJumpToKernel(UInt64 entry_point, UInt64 pml4_address, BqBootInfo* boot_info)
{
    if (entry_point == 0 || pml4_address == 0 || boot_info == NULL)
    {
        return BQ_BOOT_STATUS_INVALID_PARAMETER;
    }

    UInt64 stack_top = s_vm_ledger.stack_top;

    __asm__ volatile(
        "cli\n\t"
        "cld\n\t"
        "mov %0, %%cr3\n\t"
        "mov %1, %%rsp\n\t"
        "xor %%rbp, %%rbp\n\t"
        "pushq $0\n\t"
        "jmp *%2\n\t"
        :
        : "r"(pml4_address), "r"(stack_top), "r"(entry_point), "D"(boot_info)
        : "memory"
    );

    return BQ_BOOT_STATUS_SUCCESS;
}
