// Generated by AI under BqRetialis Architectural Specifications

#include "bq_boot_main.h"

static struct BqBootAcpiLedger s_acpi_ledger;

BqBootStatus BqBootAcpiFindRoot(BqBootAcpiRoot* acpi_root, EfiSystemTable* system_table)
{
    if (acpi_root == NULL || system_table == NULL || system_table->configuration_table == NULL)
    {
        return BQ_BOOT_STATUS_INVALID_PARAMETER;
    }

    acpi_root->madt = NULL;
    acpi_root->fadt = NULL;
    acpi_root->hpet = NULL;
    acpi_root->mcfg = NULL;

    struct EfiGuid acpi_20_guid =
    {
        0x8868e871,
        0xe4f1,
        0x11d3,
        { 0xbc, 0x22, 0x00, 0x80, 0xc7, 0x3c, 0x88, 0x81 }
    };

    struct EfiGuid acpi_10_guid =
    {
        0xeb9d2d30,
        0x2d88,
        0x11d3,
        { 0x9a, 0x16, 0x00, 0x90, 0x27, 0x3f, 0xc1, 0x4d }
    };

    struct BqBootAcpiRsdpDescriptor* rsdp = NULL;

    for (UInt64 i = 0; i < system_table->number_of_table_entries; i++)
    {
        struct EfiConfigurationTable* table = &system_table->configuration_table[i];

        UInt8 match_20 = (table->vendor_guid.data1 == acpi_20_guid.data1 &&
                          table->vendor_guid.data2 == acpi_20_guid.data2 &&
                          table->vendor_guid.data3 == acpi_20_guid.data3);

        if (match_20)
        {
            for (UInt32 b = 0; b < 8; b++)
            {
                if (table->vendor_guid.data4[b] != acpi_20_guid.data4[b])
                {
                    match_20 = 0;
                    break;
                }
            }
        }

        if (match_20)
        {
            rsdp = (struct BqBootAcpiRsdpDescriptor*)table->vendor_table;
            break;
        }

        UInt8 match_10 = (table->vendor_guid.data1 == acpi_10_guid.data1 &&
                          table->vendor_guid.data2 == acpi_10_guid.data2 &&
                          table->vendor_guid.data3 == acpi_10_guid.data3);

        if (match_10)
        {
            for (UInt32 b = 0; b < 8; b++)
            {
                if (table->vendor_guid.data4[b] != acpi_10_guid.data4[b])
                {
                    match_10 = 0;
                    break;
                }
            }
        }

        if (match_10 && rsdp == NULL)
        {
            rsdp = (struct BqBootAcpiRsdpDescriptor*)table->vendor_table;
        }
    }

    if (rsdp == NULL)
    {
        return BQ_BOOT_STATUS_NOT_FOUND;
    }

    if (rsdp->revision >= 2 && rsdp->xsdt_address != 0)
    {
        struct BqBootAcpiSdtHeader* xsdt = (struct BqBootAcpiSdtHeader*)rsdp->xsdt_address;
        UInt64 entry_count = (xsdt->length - sizeof(struct BqBootAcpiSdtHeader)) / sizeof(UInt64);
        UInt64* entries = (UInt64*)(rsdp->xsdt_address + sizeof(struct BqBootAcpiSdtHeader));

        for (UInt64 i = 0; i < entry_count; i++)
        {
            struct BqBootAcpiSdtHeader* sdt = (struct BqBootAcpiSdtHeader*)entries[i];
            if (sdt == NULL)
            {
                continue;
            }

            if (sdt->signature == 0x43495041)
            {
                acpi_root->madt = (struct BqBootAcpiMadt*)sdt;
            }
            else if (sdt->signature == 0x50434146)
            {
                acpi_root->fadt = (struct BqBootAcpiFadt*)sdt;
            }
            else if (sdt->signature == 0x54455048)
            {
                acpi_root->hpet = (struct BqBootAcpiHpet*)sdt;
            }
            else if (sdt->signature == 0x4746434D)
            {
                acpi_root->mcfg = (struct BqBootAcpiMcfg*)sdt;
            }
        }
    }
    else if (rsdp->rsdt_address != 0)
    {
        struct BqBootAcpiSdtHeader* rsdt = (struct BqBootAcpiSdtHeader*)(UInt64)rsdp->rsdt_address;
        UInt64 entry_count = (rsdt->length - sizeof(struct BqBootAcpiSdtHeader)) / sizeof(UInt32);
        UInt32* entries = (UInt32*)((UInt64)rsdp->rsdt_address + sizeof(struct BqBootAcpiSdtHeader));

        for (UInt64 i = 0; i < entry_count; i++)
        {
            struct BqBootAcpiSdtHeader* sdt = (struct BqBootAcpiSdtHeader*)(UInt64)entries[i];
            if (sdt == NULL)
            {
                continue;
            }

            if (sdt->signature == 0x43495041)
            {
                acpi_root->madt = (struct BqBootAcpiMadt*)sdt;
            }
            else if (sdt->signature == 0x50434146)
            {
                acpi_root->fadt = (struct BqBootAcpiFadt*)sdt;
            }
            else if (sdt->signature == 0x54455048)
            {
                acpi_root->hpet = (struct BqBootAcpiHpet*)sdt;
            }
            else if (sdt->signature == 0x4746434D)
            {
                acpi_root->mcfg = (struct BqBootAcpiMcfg*)sdt;
            }
        }
    }

    s_acpi_ledger.is_initialized = true;

    return BQ_BOOT_STATUS_SUCCESS;
}
