// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_UEFI_H
#define BQ_BOOT_UEFI_H

#include "bq_boot_types.h"

#define EFIAPI __attribute__((ms_abi))

typedef void* EfiHandle;

enum EfiAllocateType: UInt32
{
    AllocateAnyPages,
    AllocateMaxAddress,
    AllocateAddress,
    MaxAllocateType
};

enum EfiMemoryType: UInt32
{
    EfiReservedMemoryType,
    EfiLoaderCode,
    EfiLoaderData,
    EfiBootServicesCode,
    EfiBootServicesData,
    EfiRuntimeServicesCode,
    EfiRuntimeServicesData,
    EfiConventionalMemory,
    EfiUnusableMemory,
    EfiACPIReclaimMemory,
    EfiACPIMemoryNVS,
    EfiMemoryMappedIO,
    EfiMemoryMappedIOPortSpace,
    EfiPalCode,
    EfiPersistentMemory,
    EfiMaxMemoryType
};

enum EfiResetType: UInt32
{
    EfiResetCold,
    EfiResetWarm,
    EfiResetShutdown,
    EfiResetPlatformSpecific
};

struct EfiGuid
{
    UInt32 data1;
    UInt16 data2;
    UInt16 data3;
    UInt8  data4[8];
};

struct EfiTableHeader
{
    UInt64 signature;
    UInt32 revision;
    UInt32 header_size;
    UInt32 crc32;
    UInt32 reserved;
};

struct EfiMemoryDescriptor
{
    UInt32 type;
    UInt32 pad;
    UInt64 physical_start;
    UInt64 virtual_start;
    UInt64 number_of_pages;
    UInt64 attribute;
};

struct EfiSimpleTextOutputProtocol
{
    UInt64 reset;
    UInt64 (EFIAPI *output_string)(struct EfiSimpleTextOutputProtocol* this_protocol, const Char16* string);
    UInt64 test_string;
    UInt64 query_mode;
    UInt64 set_mode;
    UInt64 set_attribute;
    UInt64 clear_screen;
    UInt64 set_cursor_position;
    UInt64 enable_cursor;
    void*  mode;
};

struct EfiBootServices
{
    struct EfiTableHeader header;

    UInt64 raise_tpl;
    UInt64 restore_tpl;

    UInt64 (EFIAPI *allocate_pages)(enum EfiAllocateType type, enum EfiMemoryType memory_type, UInt64 pages, UInt64* memory);
    UInt64 (EFIAPI *free_pages)(UInt64 memory, UInt64 pages);
    UInt64 (EFIAPI *get_memory_map)(UInt64* memory_map_size, struct EfiMemoryDescriptor* memory_map, UInt64* map_key, UInt64* descriptor_size, UInt32* descriptor_version);
    UInt64 (EFIAPI *allocate_pool)(enum EfiMemoryType pool_type, UInt64 size, void** buffer);
    UInt64 (EFIAPI *free_pool)(void* buffer);

    UInt64 create_event;
    UInt64 set_timer;
    UInt64 wait_for_event;
    UInt64 signal_event;
    UInt64 close_event;
    UInt64 check_event;

    UInt64 install_protocol_interface;
    UInt64 reinstall_protocol_interface;
    UInt64 uninstall_protocol_interface;
    UInt64 (EFIAPI *handle_protocol)(EfiHandle handle, struct EfiGuid* protocol, void** interface);
    void*  reserved;
    UInt64 register_protocol_notify;
    UInt64 (EFIAPI *locate_handle)(UInt64 search_type, struct EfiGuid* protocol, void* search_key, UInt64* buffer_size, EfiHandle* buffer);
    UInt64 (EFIAPI *locate_device_path)(struct EfiGuid* protocol, void** device_path, EfiHandle* device);
    UInt64 install_configuration_table;

    UInt64 load_image;
    UInt64 start_image;
    UInt64 exit;
    UInt64 unload_image;
    UInt64 (EFIAPI *exit_boot_services)(EfiHandle image_handle, UInt64 map_key);

    UInt64 get_next_monotonic_count;
    UInt64 (EFIAPI *stall)(UInt64 microseconds);
    UInt64 set_watchdog_timer;

    UInt64 connect_controller;
    UInt64 disconnect_controller;

    UInt64 (EFIAPI *open_protocol)(EfiHandle handle, struct EfiGuid* protocol, void** interface, EfiHandle agent_handle, EfiHandle controller_handle, UInt32 attributes);
    UInt64 close_protocol;
    UInt64 open_protocol_information;

    UInt64 protocols_per_handle;
    UInt64 (EFIAPI *locate_handle_buffer)(UInt64 search_type, struct EfiGuid* protocol, void* search_key, UInt64* no_handles, EfiHandle** buffer);
    UInt64 (EFIAPI *locate_protocol)(struct EfiGuid* protocol, void* registration, void** interface);
    UInt64 install_multiple_protocol_interfaces;
    UInt64 uninstall_multiple_protocol_interfaces;

    UInt64 calculate_crc32;

    void (EFIAPI *copy_mem)(void* destination, const void* source, UInt64 length);
    void (EFIAPI *set_mem)(void* buffer, UInt64 size, UInt8 value);
    UInt64 create_event_ex;
};

struct EfiRuntimeServices
{
    struct EfiTableHeader header;
    UInt64 get_time;
    UInt64 set_time;
    UInt64 get_wakeup_time;
    UInt64 set_wakeup_time;
    UInt64 set_virtual_address_map;
    UInt64 convert_pointer;
    UInt64 get_variable;
    UInt64 get_next_variable_name;
    UInt64 set_variable;
    UInt64 get_next_high_monotonic_count;
    void (EFIAPI *reset_system)(enum EfiResetType reset_type, UInt64 reset_status, UInt64 data_size, void* reset_data);
};

struct EfiConfigurationTable
{
    struct EfiGuid vendor_guid;
    void*          vendor_table;
};

struct EfiSystemTable
{
    struct EfiTableHeader               header;
    Char16*                             firmware_vendor;
    UInt32                              firmware_revision;
    EfiHandle                           console_in_handle;
    void*                               con_in;
    EfiHandle                           console_out_handle;
    struct EfiSimpleTextOutputProtocol* con_out;
    EfiHandle                           standard_error_handle;
    struct EfiSimpleTextOutputProtocol* std_err;
    struct EfiRuntimeServices*          runtime_services;
    struct EfiBootServices*             boot_services;
    UInt64                              number_of_table_entries;
    struct EfiConfigurationTable*       configuration_table;
};

struct EfiLoadedImageProtocol
{
    UInt32                     revision;
    EfiHandle                  parent_handle;
    struct EfiSystemTable*     system_table;
    EfiHandle                  device_handle;
    void*                      file_path;
    void*                      reserved;
    UInt32                     load_options_size;
    void*                      load_options;
    void*                      image_base;
    UInt64                     image_size;
    enum EfiMemoryType         image_code_type;
    enum EfiMemoryType         image_data_type;
    UInt64                     unload;
};

struct EfiFileInfo
{
    UInt64 size;
    UInt64 file_size;
    UInt64 physical_size;
    UInt64 create_time[2];
    UInt64 last_access_time[2];
    UInt64 modification_time[2];
    UInt64 attribute;
    Char16 file_name[1];
};

struct EfiFileProtocol
{
    UInt64 revision;
    UInt64 (EFIAPI *open)(struct EfiFileProtocol* this_protocol, struct EfiFileProtocol** new_handle, const Char16* file_name, UInt64 open_mode, UInt64 attributes);
    UInt64 (EFIAPI *close)(struct EfiFileProtocol* this_protocol);
    UInt64 (EFIAPI *delete_file)(struct EfiFileProtocol* this_protocol);
    UInt64 (EFIAPI *read)(struct EfiFileProtocol* this_protocol, UInt64* buffer_size, void* buffer);
    UInt64 (EFIAPI *write)(struct EfiFileProtocol* this_protocol, UInt64* buffer_size, const void* buffer);
    UInt64 (EFIAPI *get_position)(struct EfiFileProtocol* this_protocol, UInt64* position);
    UInt64 (EFIAPI *set_position)(struct EfiFileProtocol* this_protocol, UInt64 position);
    UInt64 (EFIAPI *get_info)(struct EfiFileProtocol* this_protocol, struct EfiGuid* information_type, UInt64* buffer_size, void* buffer);
    UInt64 (EFIAPI *set_info)(struct EfiFileProtocol* this_protocol, struct EfiGuid* information_type, UInt64 buffer_size, void* buffer);
    UInt64 (EFIAPI *flush)(struct EfiFileProtocol* this_protocol);
};

struct EfiSimpleFileSystemProtocol
{
    UInt64 revision;
    UInt64 (EFIAPI *open_volume)(struct EfiSimpleFileSystemProtocol* this_protocol, struct EfiFileProtocol** root);
};

struct EfiGraphicsOutputModeInformation
{
    UInt32 version;
    UInt32 horizontal_resolution;
    UInt32 vertical_resolution;
    UInt32 pixel_format;
    UInt32 red_mask;
    UInt32 green_mask;
    UInt32 blue_mask;
    UInt32 reserved_mask;
    UInt32 pixels_per_scan_line;
};

struct EfiGraphicsOutputProtocolMode
{
    UInt32                                   max_mode;
    UInt32                                   mode;
    struct EfiGraphicsOutputModeInformation* info;
    UInt64                                   size_of_info;
    UInt64                                   frame_buffer_base;
    UInt64                                   frame_buffer_size;
};

struct EfiGraphicsOutputProtocol
{
    UInt64 (EFIAPI *query_mode)(struct EfiGraphicsOutputProtocol* this_protocol, UInt32 mode_number, UInt64* size_of_info, struct EfiGraphicsOutputModeInformation** info);
    UInt64 (EFIAPI *set_mode)(struct EfiGraphicsOutputProtocol* this_protocol, UInt32 mode_number);
    UInt64 blt;
    struct EfiGraphicsOutputProtocolMode* mode;
};

#endif
