// Generated by AI under BqRetialis Architectural Specifications

#include "bq_boot_main.h"

static struct BqBootElfLedger s_elf_ledger;

BqBootStatus BqBootElfLoad(BqBootKernelLayout* kernel_layout, UInt64* entry_point, EfiSystemTable* system_table, EfiHandle image_handle, const Char16* kernel_path)
{
    if (kernel_layout == NULL || entry_point == NULL || system_table == NULL ||
        system_table->boot_services == NULL || image_handle == NULL || kernel_path == NULL)
    {
        return BQ_BOOT_STATUS_INVALID_PARAMETER;
    }

    struct EfiGuid loaded_image_guid =
    {
        0x5b1b31a1,
        0x9562,
        0x11d2,
        { 0x8e, 0x3f, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
    };

    struct EfiGuid fs_guid =
    {
        0x964e5b22,
        0x6459,
        0x11d2,
        { 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
    };

    struct EfiLoadedImageProtocol* loaded_image = NULL;
    UInt64 status = system_table->boot_services->handle_protocol(image_handle, &loaded_image_guid, (void**)&loaded_image);
    if (status != 0 || loaded_image == NULL)
    {
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    struct EfiSimpleFileSystemProtocol* fs = NULL;
    status = system_table->boot_services->handle_protocol(loaded_image->device_handle, &fs_guid, (void**)&fs);
    if (status != 0 || fs == NULL)
    {
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    struct EfiFileProtocol* root = NULL;
    status = fs->open_volume(fs, &root);
    if (status != 0 || root == NULL)
    {
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    struct EfiFileProtocol* file = NULL;
    status = root->open(root, &file, kernel_path, 1, 0);
    if (status != 0 || file == NULL)
    {
        root->close(root);
        return BQ_BOOT_STATUS_NOT_FOUND;
    }

    struct BqBootElfHeader header;
    UInt64 header_size = sizeof(struct BqBootElfHeader);
    status = file->read(file, &header_size, &header);
    if (status != 0 || header_size != sizeof(struct BqBootElfHeader))
    {
        file->close(file);
        root->close(root);
        return BQ_BOOT_STATUS_LOAD_ERROR;
    }

    if (header.ident[0] != 0x7F || header.ident[1] != 'E' ||
        header.ident[2] != 'L'  || header.ident[3] != 'F' ||
        header.ident[4] != 2    || header.ident[5] != 1   ||
        header.machine != 0x3E)
    {
        file->close(file);
        root->close(root);
        return BQ_BOOT_STATUS_LOAD_ERROR;
    }

    UInt64 ph_size = (UInt64)header.phnum * sizeof(struct BqBootElfProgramHeader);
    struct BqBootElfProgramHeader* ph_table = NULL;

    status = system_table->boot_services->allocate_pool(EfiLoaderData, ph_size, (void**)&ph_table);
    if (status != 0 || ph_table == NULL)
    {
        file->close(file);
        root->close(root);
        return BQ_BOOT_STATUS_OUT_OF_RESOURCES;
    }

    file->set_position(file, header.phoff);
    status = file->read(file, &ph_size, ph_table);
    if (status != 0)
    {
        system_table->boot_services->free_pool(ph_table);
        file->close(file);
        root->close(root);
        return BQ_BOOT_STATUS_LOAD_ERROR;
    }

    UInt64 min_phys = ~0ULL;
    UInt64 max_phys = 0ULL;
    UInt64 min_virt = ~0ULL;

    for (UInt32 i = 0; i < header.phnum; i++)
    {
        struct BqBootElfProgramHeader* ph = &ph_table[i];

        if (ph->type != 1 || ph->memsz == 0)
        {
            continue;
        }

        UInt64 paddr        = ph->paddr;
        UInt64 memsz        = ph->memsz;
        UInt64 filesz       = ph->filesz;
        UInt64 page_aligned = paddr & ~0xFFFULL;
        UInt64 end_addr     = (paddr + memsz + 0xFFFULL) & ~0xFFFULL;
        UInt64 page_count   = (end_addr - page_aligned) / 4096ULL;
        UInt64 alloc_target = page_aligned;
        UInt64 alloc_status = system_table->boot_services->allocate_pages(AllocateAddress, EfiLoaderData, page_count, &alloc_target);
        if (alloc_status != 0)
        {
            system_table->boot_services->free_pool(ph_table);
            file->close(file);
            root->close(root);
            return BQ_BOOT_STATUS_OUT_OF_RESOURCES;
        }

        system_table->boot_services->set_mem((void*)page_aligned, page_count * 4096ULL, 0);

        if (filesz > 0)
        {
            file->set_position(file, ph->offset);
            UInt64 read_bytes = filesz;
            file->read(file, &read_bytes, (void*)paddr);
        }

        if (paddr < min_phys)
        {
            min_phys = paddr;
        }

        if (paddr + memsz > max_phys)
        {
            max_phys = paddr + memsz;
        }

        if (ph->vaddr < min_virt)
        {
            min_virt = ph->vaddr;
        }
    }

    system_table->boot_services->free_pool(ph_table);
    file->close(file);
    root->close(root);

    kernel_layout->physical_base = min_phys;
    kernel_layout->virtual_base  = min_virt;
    kernel_layout->region_size   = max_phys - min_phys;
    *entry_point                 = header.entry;

    s_elf_ledger.is_loaded = true;

    return BQ_BOOT_STATUS_SUCCESS;
}

BqBootStatus BqBootElfLoadModules(BqBootInfo* boot_info, EfiSystemTable* system_table, EfiHandle image_handle)
{
    if (boot_info == NULL || system_table == NULL || system_table->boot_services == NULL || image_handle == NULL)
    {
        return BQ_BOOT_STATUS_INVALID_PARAMETER;
    }

    struct EfiGuid loaded_image_guid =
    {
        0x5b1b31a1,
        0x9562,
        0x11d2,
        { 0x8e, 0x3f, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
    };

    struct EfiGuid fs_guid =
    {
        0x964e5b22,
        0x6459,
        0x11d2,
        { 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b }
    };

    struct EfiLoadedImageProtocol* loaded_image = NULL;
    UInt64 status = system_table->boot_services->handle_protocol(image_handle, &loaded_image_guid, (void**)&loaded_image);
    if (status != 0 || loaded_image == NULL)
    {
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    struct EfiSimpleFileSystemProtocol* fs = NULL;
    status = system_table->boot_services->handle_protocol(loaded_image->device_handle, &fs_guid, (void**)&fs);
    if (status != 0 || fs == NULL)
    {
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    struct EfiFileProtocol* root = NULL;
    status = fs->open_volume(fs, &root);
    if (status != 0 || root == NULL)
    {
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    const Char16* uefi_paths[5] =
    {
        (const Char16*)u"\\System\\Drivers\\Ps2Keyboard.elf",
        (const Char16*)u"\\System\\Drivers\\Ps2Mouse.elf",
        (const Char16*)u"\\System\\Drivers\\GopDisplay.elf",
        (const Char16*)u"\\System\\Drivers\\AtaStorage.elf",
        (const Char16*)u"\\System\\Services\\Desktop.elf"
    };

    const Char16* alt_uefi_paths[5] =
    {
        (const Char16*)u"System\\Drivers\\Ps2Keyboard.elf",
        (const Char16*)u"System\\Drivers\\Ps2Mouse.elf",
        (const Char16*)u"System\\Drivers\\GopDisplay.elf",
        (const Char16*)u"System\\Drivers\\AtaStorage.elf",
        (const Char16*)u"System\\Services\\Desktop.elf"
    };

    const char* vfs_paths[5] =
    {
        "\\System\\Drivers\\Ps2Keyboard.elf",
        "\\System\\Drivers\\Ps2Mouse.elf",
        "\\System\\Drivers\\GopDisplay.elf",
        "\\System\\Drivers\\AtaStorage.elf",
        "\\System\\Services\\Desktop.elf"
    };

    for (UInt32 i = 0; i < 5; i++)
    {
        struct EfiFileProtocol* file = NULL;
        status = root->open(root, &file, uefi_paths[i], 1, 0);
        if (status != 0 || file == NULL)
        {
            status = root->open(root, &file, alt_uefi_paths[i], 1, 0);
        }

        if (status != 0 || file == NULL)
        {
            continue;
        }

        UInt64 file_size = 0;
        file->set_position(file, 0xFFFFFFFFFFFFFFFFULL);
        file->get_position(file, &file_size);
        file->set_position(file, 0);

        if (file_size == 0)
        {
            file->close(file);
            continue;
        }

        UInt64 page_count = (file_size + 4095ULL) / 4096ULL;
        UInt64 alloc_target = 0xFFFFFFFFULL;
        status = system_table->boot_services->allocate_pages(AllocateMaxAddress, EfiLoaderData, page_count, &alloc_target);
        if (status != 0 || alloc_target == 0)
        {
            status = system_table->boot_services->allocate_pages(AllocateAnyPages, EfiLoaderData, page_count, &alloc_target);
            if (status != 0 || alloc_target == 0)
            {
                file->close(file);
                continue;
            }
        }

        system_table->boot_services->set_mem((void*)alloc_target, page_count * 4096ULL, 0);

        UInt64 read_bytes = file_size;
        file->read(file, &read_bytes, (void*)alloc_target);
        file->close(file);

        UInt32 mod_idx = boot_info->module_count;
        if (mod_idx < 16)
        {
            boot_info->modules[mod_idx].physical_base = alloc_target;
            boot_info->modules[mod_idx].size          = file_size;

            UInt32 p = 0;
            while (vfs_paths[i][p] != '\0' && p < 127)
            {
                boot_info->modules[mod_idx].path[p] = vfs_paths[i][p];
                p++;
            }
            boot_info->modules[mod_idx].path[p] = '\0';

            boot_info->module_count++;
        }
    }

    root->close(root);

    return BQ_BOOT_STATUS_SUCCESS;
}
