// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_FRAMEBUFFER_H
#define BQ_BOOT_FRAMEBUFFER_H

#include "bq_boot_types.h"

struct BqBootFramebuffer
{
    UInt64 physical_base;
    UInt64 region_size;
    UInt32 width;
    UInt32 height;
    UInt32 pitch;
    UInt32 bpp;
}
__attribute__((packed));

#endif
