// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_GOP_H
#define BQ_BOOT_GOP_H

#include "bq_boot_types.h"

struct BqBootGopLedger
{
    UInt32 is_initialized;
};

#endif
