// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_ELF_H
#define BQ_BOOT_ELF_H

#include "bq_boot_types.h"

struct BqBootElfHeader
{
    UInt8  ident[16];
    UInt16 type;
    UInt16 machine;
    UInt32 version;
    UInt64 entry;
    UInt64 phoff;
    UInt64 shoff;
    UInt32 flags;
    UInt16 ehsize;
    UInt16 phentsize;
    UInt16 phnum;
    UInt16 shentsize;
    UInt16 shnum;
    UInt16 shstrndx;
}
__attribute__((packed));

struct BqBootElfProgramHeader
{
    UInt32 type;
    UInt32 flags;
    UInt64 offset;
    UInt64 vaddr;
    UInt64 paddr;
    UInt64 filesz;
    UInt64 memsz;
    UInt64 align;
}
__attribute__((packed));

struct BqBootElfLedger
{
    UInt32 is_loaded;
};

#endif
