// Generated by AI under BqRetialis Architectural Specifications

#include "bq_boot_main.h"

static struct BqBootGopLedger s_gop_ledger;

BqBootStatus BqBootGopInitialize(BqBootFramebuffer* framebuffer, EfiSystemTable* system_table)
{
    if (framebuffer == NULL || system_table == NULL || system_table->boot_services == NULL)
    {
        return BQ_BOOT_STATUS_INVALID_PARAMETER;
    }

    struct EfiGuid gop_guid =
    {
        0x9042a9de,
        0x23dc,
        0x4a38,
        { 0x96, 0xfb, 0x7a, 0xde, 0xd0, 0x80, 0x51, 0x6a }
    };

    struct EfiGraphicsOutputProtocol* gop = NULL;

    UInt64 status = system_table->boot_services->locate_protocol(&gop_guid, NULL, (void**)&gop);
    if (status != 0 || gop == NULL || gop->mode == NULL || gop->mode->info == NULL)
    {
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    framebuffer->physical_base = gop->mode->frame_buffer_base;
    framebuffer->region_size   = gop->mode->frame_buffer_size;
    framebuffer->width         = gop->mode->info->horizontal_resolution;
    framebuffer->height        = gop->mode->info->vertical_resolution;
    framebuffer->pitch         = gop->mode->info->pixels_per_scan_line;
    framebuffer->bpp           = 32;

    s_gop_ledger.is_initialized = true;

    return BQ_BOOT_STATUS_SUCCESS;
}
