// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_MEMORY_MAP_H
#define BQ_BOOT_MEMORY_MAP_H

#include "bq_boot_types.h"

enum BqBootMemoryMapHardwareType: UInt32
{
    BQ_BOOT_MEMORY_MAP_TYPE_INVALID          = 0,
    BQ_BOOT_MEMORY_MAP_TYPE_USABLE           = 1,
    BQ_BOOT_MEMORY_MAP_TYPE_RESERVED         = 2,
    BQ_BOOT_MEMORY_MAP_TYPE_ACPI_RECLAIMABLE = 3,
    BQ_BOOT_MEMORY_MAP_TYPE_ACPI_NVS         = 4,
    BQ_BOOT_MEMORY_MAP_TYPE_BAD              = 5,
    BQ_BOOT_MEMORY_MAP_TYPE_KERNEL           = 6
};

enum BqBootMemoryMapAcpiAttribute: UInt32
{
    BQ_BOOT_MEMORY_MAP_ACPI_NONE         = 0x00000000,
    BQ_BOOT_MEMORY_MAP_ACPI_ENABLED      = 0x00000001,
    BQ_BOOT_MEMORY_MAP_ACPI_NON_VOLATILE = 0x00000002,
    BQ_BOOT_MEMORY_MAP_ACPI_SLOW_ACCESS  = 0x00000004,
    BQ_BOOT_MEMORY_MAP_ACPI_ERROR_LOG    = 0x00000008
};

struct BqBootMemoryMapEntry
{
    UInt64                            base_address;
    UInt64                            region_size;
    enum BqBootMemoryMapHardwareType  hardware_type;
    enum BqBootMemoryMapAcpiAttribute acpi_attributes;
}
__attribute__((packed));

struct BqBootMemoryMap
{
    struct BqBootMemoryMapEntry* entries;
    UInt32                       count;
};

struct BqBootMemoryMapLedger
{
    UInt64                       uefi_buffer;
    UInt64                       uefi_buffer_size;
    struct BqBootMemoryMapEntry* entries;
    UInt64                       max_entries;
    struct BqBootMemoryMap*      memory_map;
    UInt32                       count;
};

#endif
