// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_TYPES_H
#define BQ_BOOT_TYPES_H

typedef __UINT8_TYPE__ Bool;
#define true 1
#define false 0

typedef __UINT8_TYPE__ UInt8;
typedef __UINT16_TYPE__ UInt16;
typedef __UINT32_TYPE__ UInt32;
typedef __UINT64_TYPE__ UInt64;

typedef __INT8_TYPE__ Int8;
typedef __INT16_TYPE__ Int16;
typedef __INT32_TYPE__ Int32;
typedef __INT64_TYPE__ Int64;

typedef __UINT_LEAST8_TYPE__ UIntLeast8;
typedef __UINT_LEAST16_TYPE__ UIntLeast16;
typedef __UINT_LEAST32_TYPE__ UIntLeast32;
typedef __UINT_LEAST64_TYPE__ UIntLeast64;

typedef __INT_LEAST8_TYPE__ IntLeast8;
typedef __INT_LEAST16_TYPE__ IntLeast16;
typedef __INT_LEAST32_TYPE__ IntLeast32;
typedef __INT_LEAST64_TYPE__ IntLeast64;

typedef __UINT_FAST8_TYPE__ UIntFast8;
typedef __UINT_FAST16_TYPE__ UIntFast16;
typedef __UINT_FAST32_TYPE__ UIntFast32;
typedef __UINT_FAST64_TYPE__ UIntFast64;

typedef __INT_FAST8_TYPE__ IntFast8;
typedef __INT_FAST16_TYPE__ IntFast16;
typedef __INT_FAST32_TYPE__ IntFast32;
typedef __INT_FAST64_TYPE__ IntFast64;

typedef __UINTPTR_TYPE__ UIntPtr;
typedef __INTPTR_TYPE__ IntPtr;
typedef __SIZE_TYPE__ Size;
typedef __PTRDIFF_TYPE__ PtrDiff;
typedef __UINTMAX_TYPE__ UIntMax;
typedef __INTMAX_TYPE__ IntMax;

typedef __WCHAR_TYPE__ WChar;
typedef __WINT_TYPE__ WInt;
typedef __SIG_ATOMIC_TYPE__ SigAtomic;
typedef __CHAR16_TYPE__ Char16;
typedef __CHAR32_TYPE__ Char32;

typedef __builtin_va_list VaList;

#define VaStart(ap, param) __builtin_va_start(ap, param)
#define VaEnd(ap) __builtin_va_end(ap)
#define VaArg(ap, type) __builtin_va_arg(ap, type)
#define VaCopy(dest, src) __builtin_va_copy(dest, src)

#define NULL ((void*)0)
#define OffsetOf(type, member) __builtin_offsetof(type, member)
#define AlignAs(x) _Alignas(x)
#define AlignOf(x) _Alignof(x)
#define NoReturn _Noreturn

#define UINT8_MAX __UINT8_MAX__
#define UINT16_MAX __UINT16_MAX__
#define UINT32_MAX __UINT32_MAX__
#define UINT64_MAX __UINT64_MAX__

#define INT8_MAX __INT8_MAX__
#define INT16_MAX __INT16_MAX__
#define INT32_MAX __INT32_MAX__
#define INT64_MAX __INT64_MAX__

#define INT8_MIN (-__INT8_MAX__ - 1)
#define INT16_MIN (-__INT16_MAX__ - 1)
#define INT32_MIN (-__INT32_MAX__ - 1)
#define INT64_MIN (-__INT64_MAX__ - 1)

#define UINT_LEAST8_MAX __UINT_LEAST8_MAX__
#define UINT_LEAST16_MAX __UINT_LEAST16_MAX__
#define UINT_LEAST32_MAX __UINT_LEAST32_MAX__
#define UINT_LEAST64_MAX __UINT_LEAST64_MAX__

#define INT_LEAST8_MAX __INT_LEAST8_MAX__
#define INT_LEAST16_MAX __INT_LEAST16_MAX__
#define INT_LEAST32_MAX __INT_LEAST32_MAX__
#define INT_LEAST64_MAX __INT_LEAST64_MAX__

#define INT_LEAST8_MIN (-__INT_LEAST8_MAX__ - 1)
#define INT_LEAST16_MIN (-__INT_LEAST16_MAX__ - 1)
#define INT_LEAST32_MIN (-__INT_LEAST32_MAX__ - 1)
#define INT_LEAST64_MIN (-__INT_LEAST64_MAX__ - 1)

#define UINT_FAST8_MAX __UINT_FAST8_MAX__
#define UINT_FAST16_MAX __UINT_FAST16_MAX__
#define UINT_FAST32_MAX __UINT_FAST32_MAX__
#define UINT_FAST64_MAX __UINT_FAST64_MAX__

#define INT_FAST8_MAX __INT_FAST8_MAX__
#define INT_FAST16_MAX __INT_FAST16_MAX__
#define INT_FAST32_MAX __INT_FAST32_MAX__
#define INT_FAST64_MAX __INT_FAST64_MAX__

#define INT_FAST8_MIN (-__INT_FAST8_MAX__ - 1)
#define INT_FAST16_MIN (-__INT_FAST16_MAX__ - 1)
#define INT_FAST32_MIN (-__INT_FAST32_MAX__ - 1)
#define INT_FAST64_MIN (-__INT_FAST64_MAX__ - 1)

#define UINTPTR_MAX __UINTPTR_MAX__
#define INTPTR_MAX __INTPTR_MAX__
#define INTPTR_MIN (-__INTPTR_MAX__ - 1)
#define SIZE_MAX __SIZE_MAX__
#define PTRDIFF_MAX __PTRDIFF_MAX__
#define PTRDIFF_MIN (-__PTRDIFF_MAX__ - 1)

#define UINTMAX_MAX __UINTMAX_MAX__
#define INTMAX_MAX __INTMAX_MAX__
#define INTMAX_MIN (-__INTMAX_MAX__ - 1)
#define WCHAR_MAX __WCHAR_MAX__
#define WCHAR_MIN __WCHAR_MIN__

#endif
