// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_INFO_H
#define BQ_BOOT_INFO_H

#include "bq_boot_types.h"
#include "bq_boot_kernel_layout.h"
#include "bq_boot_memory_map.h"
#include "bq_boot_acpi.h"
#include "bq_boot_framebuffer.h"

struct BqBootModule
{
    UInt64 physical_base;
    UInt64 size;
    char   path[128];
};

struct BqBootInfo
{
    struct BqBootKernelLayout kernel_layout;
    struct BqBootMemoryMap    memory_map;
    struct BqBootAcpiRoot     acpi_root;
    struct BqBootFramebuffer  framebuffer;
    struct BqBootModule*      modules;
    UInt32                    module_count;
};

#endif
