// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_ACPI_H
#define BQ_BOOT_ACPI_H

#include "bq_boot_types.h"

struct BqBootAcpiGas
{
    UInt8  address_space_id;
    UInt8  register_bit_width;
    UInt8  register_bit_offset;
    UInt8  access_size;
    UInt64 base_address;
}
__attribute__((packed));

struct BqBootAcpiSdtHeader
{
    UInt32 signature;
    UInt32 length;
    UInt8  revision;
    UInt8  checksum;
    UInt8  oem_id[6];
    UInt8  oem_table_id[8];
    UInt32 oem_revision;
    UInt32 creator_id;
    UInt32 creator_revision;
}
__attribute__((packed));

struct BqBootAcpiMadtRecordHeader
{
    UInt8 record_type;
    UInt8 record_length;
}
__attribute__((packed));

struct BqBootAcpiMadtLocalApic
{
    struct BqBootAcpiMadtRecordHeader header;
    UInt8                             processor_id;
    UInt8                             apic_id;
    UInt32                            flags;
}
__attribute__((packed));

struct BqBootAcpiMadtIoApic
{
    struct BqBootAcpiMadtRecordHeader header;
    UInt8                             io_apic_id;
    UInt8                             reserved;
    UInt32                            io_apic_address;
    UInt32                            gsi_base;
}
__attribute__((packed));

struct BqBootAcpiMadtIrqOverride
{
    struct BqBootAcpiMadtRecordHeader header;
    UInt8                             bus_source;
    UInt8                             irq_source;
    UInt32                            gsi;
    UInt16                            flags;
}
__attribute__((packed));

struct BqBootAcpiMadtLocalApicOverride
{
    struct BqBootAcpiMadtRecordHeader header;
    UInt16                            reserved;
    UInt64                            local_apic_address;
}
__attribute__((packed));

struct BqBootAcpiMadt
{
    struct BqBootAcpiSdtHeader header;
    UInt32                     local_apic_address;
    UInt32                     flags;
}
__attribute__((packed));

struct BqBootAcpiFadt
{
    struct BqBootAcpiSdtHeader header;
    UInt32                     firmware_ctrl;
    UInt32                     dsdt_address;
    UInt8                      reserved0;
    UInt8                      preferred_pm_profile;
    UInt16                     sci_interrupt;
    UInt32                     smi_command_port;
    UInt8                      acpi_enable;
    UInt8                      acpi_disable;
    UInt8                      s4bios_req;
    UInt8                      pstate_control;
    UInt32                     pm1a_event_block;
    UInt32                     pm1b_event_block;
    UInt32                     pm1a_control_block;
    UInt32                     pm1b_control_block;
    UInt32                     pm2_control_block;
    UInt32                     pm_timer_block;
    UInt32                     gpe0_block;
    UInt32                     gpe1_block;
    UInt8                      pm1_event_length;
    UInt8                      pm1_control_length;
    UInt8                      pm2_control_length;
    UInt8                      pm_timer_length;
    UInt8                      gpe0_length;
    UInt8                      gpe1_length;
    UInt8                      gpe1_base;
    UInt8                      cstate_control;
    UInt16                     worst_c2_latency;
    UInt16                     worst_c3_latency;
    UInt16                     flush_size;
    UInt16                     flush_stride;
    UInt8                      duty_offset;
    UInt8                      duty_width;
    UInt8                      day_alarm;
    UInt8                      month_alarm;
    UInt8                      century;
    UInt16                     boot_architecture_flags;
    UInt8                      reserved1;
    UInt32                     flags;
}
__attribute__((packed));

struct BqBootAcpiHpet
{
    struct BqBootAcpiSdtHeader header;
    UInt32                     hardware_block_id;
    struct BqBootAcpiGas       base_address;
    UInt8                      hpet_number;
    UInt16                     minimum_tick;
    UInt8                      page_protection;
}
__attribute__((packed));

struct BqBootAcpiMcfgAllocation
{
    UInt64 base_address;
    UInt16 pci_segment_group;
    UInt8  start_bus;
    UInt8  end_bus;
    UInt32 reserved;
}
__attribute__((packed));

struct BqBootAcpiMcfg
{
    struct BqBootAcpiSdtHeader header;
    UInt64                     reserved;
}
__attribute__((packed));

struct BqBootAcpiRoot
{
    struct BqBootAcpiMadt* madt;
    struct BqBootAcpiFadt* fadt;
    struct BqBootAcpiHpet* hpet;
    struct BqBootAcpiMcfg* mcfg;
};

struct BqBootAcpiRsdpDescriptor
{
    UInt8  signature[8];
    UInt8  checksum;
    UInt8  oem_id[6];
    UInt8  revision;
    UInt32 rsdt_address;
    UInt32 length;
    UInt64 xsdt_address;
    UInt8  extended_checksum;
    UInt8  reserved[3];
}
__attribute__((packed));

struct BqBootAcpiLedger
{
    UInt32 is_initialized;
};

#endif
