// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_KERNEL_LAYOUT_H
#define BQ_BOOT_KERNEL_LAYOUT_H

#include "bq_boot_types.h"

struct BqBootKernelLayout
{
    UInt64 physical_base;
    UInt64 virtual_base;
    UInt64 region_size;
}
__attribute__((packed));

#endif
