// Generated by AI under BqRetialis Architectural Specifications

#include "bq_boot_main.h"

static struct BqBootMemoryMapLedger s_memory_map_ledger;

BqBootStatus BqBootMemoryMapTranslateDescriptors(
    UInt64 uefi_buf,
    UInt64 mmap_size,
    UInt64 desc_size,
    BqBootMemoryMapEntry* bq_entries,
    UInt64 max_entries,
    UInt32* entry_count)
{
    if (desc_size == 0 || bq_entries == NULL || entry_count == NULL)
    {
        return BQ_BOOT_STATUS_INVALID_PARAMETER;
    }

    UInt64 desc_count = mmap_size / desc_size;
    UInt32 count      = 0;

    for (UInt64 i = 0; i < desc_count && (UInt64)count < max_entries; i++)
    {
        struct EfiMemoryDescriptor* desc = (struct EfiMemoryDescriptor*)(uefi_buf + (i * desc_size));

        bq_entries[count].base_address    = desc->physical_start;
        bq_entries[count].region_size     = desc->number_of_pages * 4096ULL;
        bq_entries[count].acpi_attributes = BQ_BOOT_MEMORY_MAP_ACPI_NONE;

        switch (desc->type)
        {
            case EfiLoaderCode:
            case EfiLoaderData:
                bq_entries[count].hardware_type = BQ_BOOT_MEMORY_MAP_TYPE_KERNEL;
                break;

            case EfiBootServicesCode:
            case EfiBootServicesData:
            case EfiConventionalMemory:
                bq_entries[count].hardware_type = BQ_BOOT_MEMORY_MAP_TYPE_USABLE;
                break;

            case EfiACPIReclaimMemory:
                bq_entries[count].hardware_type = BQ_BOOT_MEMORY_MAP_TYPE_ACPI_RECLAIMABLE;
                break;

            case EfiACPIMemoryNVS:
                bq_entries[count].hardware_type = BQ_BOOT_MEMORY_MAP_TYPE_ACPI_NVS;
                break;

            case EfiUnusableMemory:
                bq_entries[count].hardware_type = BQ_BOOT_MEMORY_MAP_TYPE_BAD;
                break;

            default:
                bq_entries[count].hardware_type = BQ_BOOT_MEMORY_MAP_TYPE_RESERVED;
                break;
        }

        count++;
    }

    *entry_count = count;

    return BQ_BOOT_STATUS_SUCCESS;
}

BqBootStatus BqBootMemoryMapGet(BqBootMemoryMap* memory_map, UInt64* memory_map_key, EfiSystemTable* system_table)
{
    if (memory_map == NULL || memory_map_key == NULL || system_table == NULL ||
        system_table->boot_services == NULL)
    {
        return BQ_BOOT_STATUS_INVALID_PARAMETER;
    }

    UInt64 mmap_size = 0;
    UInt64 map_key   = 0;
    UInt64 desc_size = 0;
    UInt32 desc_ver  = 0;

    system_table->boot_services->get_memory_map(&mmap_size, NULL, &map_key, &desc_size, &desc_ver);

    mmap_size += 16384ULL;
    UInt64 uefi_pages = (mmap_size + 4095ULL) / 4096ULL;
    UInt64 uefi_buf   = 0xFFFFFFFFULL;

    UInt64 status = system_table->boot_services->allocate_pages(AllocateMaxAddress, EfiLoaderData, uefi_pages, &uefi_buf);
    if (status != 0 || uefi_buf == 0)
    {
        status = system_table->boot_services->allocate_pages(AllocateAnyPages, EfiLoaderData, uefi_pages, &uefi_buf);
        if (status != 0 || uefi_buf == 0)
        {
            return BQ_BOOT_STATUS_OUT_OF_RESOURCES;
        }
    }

    UInt64 max_entries = ((uefi_pages * 4096ULL) / (desc_size != 0 ? desc_size : 48ULL)) + 128ULL;
    UInt64 bq_bytes    = max_entries * sizeof(struct BqBootMemoryMapEntry);
    UInt64 bq_pages    = (bq_bytes + 4095ULL) / 4096ULL;
    UInt64 bq_buf      = 0xFFFFFFFFULL;

    status = system_table->boot_services->allocate_pages(AllocateMaxAddress, EfiLoaderData, bq_pages, &bq_buf);
    if (status != 0 || bq_buf == 0)
    {
        status = system_table->boot_services->allocate_pages(AllocateAnyPages, EfiLoaderData, bq_pages, &bq_buf);
        if (status != 0 || bq_buf == 0)
        {
            system_table->boot_services->free_pages(uefi_buf, uefi_pages);
            return BQ_BOOT_STATUS_OUT_OF_RESOURCES;
        }
    }

    system_table->boot_services->set_mem((void*)bq_buf, bq_pages * 4096ULL, 0);

    UInt64 actual_size = uefi_pages * 4096ULL;
    status = system_table->boot_services->get_memory_map(&actual_size, (struct EfiMemoryDescriptor*)uefi_buf, &map_key, &desc_size, &desc_ver);
    if (status != 0)
    {
        system_table->boot_services->free_pages(bq_buf, bq_pages);
        system_table->boot_services->free_pages(uefi_buf, uefi_pages);
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    UInt32 count = 0;
    status = BqBootMemoryMapTranslateDescriptors(
        uefi_buf,
        actual_size,
        desc_size,
        (struct BqBootMemoryMapEntry*)bq_buf,
        max_entries,
        &count
    );
    if (status != BQ_BOOT_STATUS_SUCCESS)
    {
        system_table->boot_services->free_pages(bq_buf, bq_pages);
        system_table->boot_services->free_pages(uefi_buf, uefi_pages);
        return status;
    }

    memory_map->entries = (struct BqBootMemoryMapEntry*)bq_buf;
    memory_map->count   = count;
    *memory_map_key     = map_key;

    s_memory_map_ledger.uefi_buffer      = uefi_buf;
    s_memory_map_ledger.uefi_buffer_size = uefi_pages * 4096ULL;
    s_memory_map_ledger.entries          = (struct BqBootMemoryMapEntry*)bq_buf;
    s_memory_map_ledger.max_entries      = max_entries;
    s_memory_map_ledger.memory_map       = memory_map;
    s_memory_map_ledger.count            = count;

    return BQ_BOOT_STATUS_SUCCESS;
}

BqBootStatus BqBootMemoryMapExitBootServices(BqBootMemoryMap* memory_map, EfiSystemTable* system_table, EfiHandle image_handle, UInt64 memory_map_key)
{
    if (system_table == NULL || system_table->boot_services == NULL || image_handle == NULL)
    {
        return BQ_BOOT_STATUS_INVALID_PARAMETER;
    }

    struct BqBootMemoryMap* target_map = memory_map;
    if (target_map == NULL)
    {
        target_map = s_memory_map_ledger.memory_map;
    }

    UInt64 status = system_table->boot_services->exit_boot_services(image_handle, memory_map_key);
    if (status == 0)
    {
        return BQ_BOOT_STATUS_SUCCESS;
    }

    if (s_memory_map_ledger.uefi_buffer == 0 || s_memory_map_ledger.uefi_buffer_size == 0 ||
        s_memory_map_ledger.entries == NULL || s_memory_map_ledger.max_entries == 0)
    {
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    UInt64 mmap_size = s_memory_map_ledger.uefi_buffer_size;
    UInt64 map_key   = 0;
    UInt64 desc_size = 0;
    UInt32 desc_ver  = 0;

    status = system_table->boot_services->get_memory_map(
        &mmap_size,
        (struct EfiMemoryDescriptor*)s_memory_map_ledger.uefi_buffer,
        &map_key,
        &desc_size,
        &desc_ver
    );
    if (status != 0)
    {
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    UInt32 count = 0;
    status = BqBootMemoryMapTranslateDescriptors(
        s_memory_map_ledger.uefi_buffer,
        mmap_size,
        desc_size,
        s_memory_map_ledger.entries,
        s_memory_map_ledger.max_entries,
        &count
    );
    if (status != BQ_BOOT_STATUS_SUCCESS)
    {
        return status;
    }

    s_memory_map_ledger.count = count;
    if (target_map != NULL)
    {
        target_map->entries = s_memory_map_ledger.entries;
        target_map->count   = count;
    }

    status = system_table->boot_services->exit_boot_services(image_handle, map_key);
    if (status != 0)
    {
        return BQ_BOOT_STATUS_DEVICE_ERROR;
    }

    return BQ_BOOT_STATUS_SUCCESS;
}
