// Generated by AI under BqRetialis Architectural Specifications

#include "bq_boot_main.h"

void BqBootFatalError(EfiSystemTable* system_table, const Char16* message)
{
    if (system_table != NULL && system_table->con_out != NULL && message != NULL)
    {
        system_table->con_out->output_string(system_table->con_out, message);
    }

    if (system_table != NULL && system_table->boot_services != NULL && system_table->boot_services->stall != NULL)
    {
        system_table->boot_services->stall(3000000ULL);
    }
}

BqBootStatus EFIAPI EfiMain(EfiHandle image_handle, EfiSystemTable* system_table)
{
    if (image_handle == NULL || system_table == NULL || system_table->boot_services == NULL)
    {
        return BQ_BOOT_STATUS_INVALID_PARAMETER;
    }

    UInt64 boot_info_addr = 0xFFFFFFFFULL;
    UInt64 status_val = system_table->boot_services->allocate_pages(AllocateMaxAddress, EfiLoaderData, 1, &boot_info_addr);
    if (status_val != 0 || boot_info_addr == 0)
    {
        status_val = system_table->boot_services->allocate_pages(AllocateAnyPages, EfiLoaderData, 1, &boot_info_addr);
        if (status_val != 0 || boot_info_addr == 0)
        {
            BqBootFatalError(system_table, (const Char16*)u"BqRadialisBoot: Failed to allocate boot info memory\r\n");
            return BQ_BOOT_STATUS_OUT_OF_RESOURCES;
        }
    }

    struct BqBootInfo* boot_info = (struct BqBootInfo*)boot_info_addr;
    system_table->boot_services->set_mem(boot_info, sizeof(struct BqBootInfo), 0);
    boot_info->modules = (struct BqBootModule*)((UInt64)boot_info_addr + 256ULL);
    boot_info->module_count = 0;

    BqBootStatus status = BqBootGopInitialize(&boot_info->framebuffer, system_table);
    if (status != BQ_BOOT_STATUS_SUCCESS)
    {
        BqBootFatalError(system_table, (const Char16*)u"BqRadialisBoot: Graphics Output Protocol (GOP) initialization failed\r\n");
        return status;
    }

    status = BqBootAcpiFindRoot(&boot_info->acpi_root, system_table);
    if (status != BQ_BOOT_STATUS_SUCCESS)
    {
        BqBootFatalError(system_table, (const Char16*)u"BqRadialisBoot: ACPI table detection failed\r\n");
        return status;
    }

    UInt64 entry_point = 0;
    status = BqBootElfLoad(&boot_info->kernel_layout, &entry_point, system_table, image_handle, (const Char16*)u"\\BqRadialis.elf");
    if (status != BQ_BOOT_STATUS_SUCCESS)
    {
        status = BqBootElfLoad(&boot_info->kernel_layout, &entry_point, system_table, image_handle, (const Char16*)u"BqRadialis.elf");
    }

    if (status != BQ_BOOT_STATUS_SUCCESS)
    {
        BqBootFatalError(system_table, (const Char16*)u"BqRadialisBoot: Failed to locate or load kernel executable (BqRadialis.elf)\r\n");
        return status;
    }

    BqBootElfLoadModules(boot_info, system_table, image_handle);

    UInt64 pml4_address = 0;
    status = BqBootVmBuildPageTables(&pml4_address, system_table, &boot_info->kernel_layout, &boot_info->framebuffer);
    if (status != BQ_BOOT_STATUS_SUCCESS)
    {
        BqBootFatalError(system_table, (const Char16*)u"BqRadialisBoot: Page table initialization failed\r\n");
        return status;
    }

    UInt64 memory_map_key = 0;
    status = BqBootMemoryMapGet(&boot_info->memory_map, &memory_map_key, system_table);
    if (status != BQ_BOOT_STATUS_SUCCESS)
    {
        BqBootFatalError(system_table, (const Char16*)u"BqRadialisBoot: Failed to retrieve memory map\r\n");
        return status;
    }

    status = BqBootMemoryMapExitBootServices(&boot_info->memory_map, system_table, image_handle, memory_map_key);
    if (status != BQ_BOOT_STATUS_SUCCESS)
    {
        BqBootFatalError(system_table, (const Char16*)u"BqRadialisBoot: ExitBootServices failed\r\n");
        return status;
    }

    return BqBootVmJumpToKernel(entry_point, pml4_address, boot_info);
}
