// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_STATUS_H
#define BQ_BOOT_STATUS_H

#include "bq_boot_types.h"

enum BqBootStatus: UInt32
{
    BQ_BOOT_STATUS_SUCCESS            = 0,
    BQ_BOOT_STATUS_INVALID_PARAMETER  = 1,
    BQ_BOOT_STATUS_OUT_OF_RESOURCES   = 2,
    BQ_BOOT_STATUS_DEVICE_ERROR       = 3,
    BQ_BOOT_STATUS_UNSUPPORTED        = 4,
    BQ_BOOT_STATUS_NOT_FOUND          = 5,
    BQ_BOOT_STATUS_LOAD_ERROR         = 6,
    BQ_BOOT_STATUS_SECURITY_VIOLATION = 7,
    BQ_BOOT_STATUS_BUFFER_TOO_SMALL   = 8
};

#endif
