// Generated by AI under BqRetialis Architectural Specifications

#ifndef BQ_BOOT_MAIN_H
#define BQ_BOOT_MAIN_H

#include "bq_boot_types.h"
#include "bq_boot_status.h"
#include "bq_boot_uefi.h"
#include "bq_boot_framebuffer.h"
#include "bq_boot_gop.h"
#include "bq_boot_acpi.h"
#include "bq_boot_kernel_layout.h"
#include "bq_boot_elf.h"
#include "bq_boot_vm.h"
#include "bq_boot_memory_map.h"
#include "bq_boot_info.h"

typedef enum   BqBootStatus BqBootStatus;

typedef enum   EfiAllocateType EfiAllocateType;
typedef enum   EfiMemoryType EfiMemoryType;
typedef enum   EfiResetType EfiResetType;
typedef struct EfiGuid EfiGuid;
typedef struct EfiTableHeader EfiTableHeader;
typedef struct EfiMemoryDescriptor EfiMemoryDescriptor;
typedef struct EfiSimpleTextOutputProtocol EfiSimpleTextOutputProtocol;
typedef struct EfiBootServices EfiBootServices;
typedef struct EfiRuntimeServices EfiRuntimeServices;
typedef struct EfiConfigurationTable EfiConfigurationTable;
typedef struct EfiSystemTable EfiSystemTable;
typedef struct EfiLoadedImageProtocol EfiLoadedImageProtocol;
typedef struct EfiFileInfo EfiFileInfo;
typedef struct EfiFileProtocol EfiFileProtocol;
typedef struct EfiSimpleFileSystemProtocol EfiSimpleFileSystemProtocol;
typedef struct EfiGraphicsOutputModeInformation EfiGraphicsOutputModeInformation;
typedef struct EfiGraphicsOutputProtocolMode EfiGraphicsOutputProtocolMode;
typedef struct EfiGraphicsOutputProtocol EfiGraphicsOutputProtocol;

typedef struct BqBootFramebuffer BqBootFramebuffer;

typedef struct BqBootGopLedger BqBootGopLedger;

typedef struct BqBootAcpiGas BqBootAcpiGas;
typedef struct BqBootAcpiSdtHeader BqBootAcpiSdtHeader;
typedef struct BqBootAcpiMadtRecordHeader BqBootAcpiMadtRecordHeader;
typedef struct BqBootAcpiMadtLocalApic BqBootAcpiMadtLocalApic;
typedef struct BqBootAcpiMadtIoApic BqBootAcpiMadtIoApic;
typedef struct BqBootAcpiMadtIrqOverride BqBootAcpiMadtIrqOverride;
typedef struct BqBootAcpiMadtLocalApicOverride BqBootAcpiMadtLocalApicOverride;
typedef struct BqBootAcpiMadt BqBootAcpiMadt;
typedef struct BqBootAcpiFadt BqBootAcpiFadt;
typedef struct BqBootAcpiHpet BqBootAcpiHpet;
typedef struct BqBootAcpiMcfgAllocation BqBootAcpiMcfgAllocation;
typedef struct BqBootAcpiMcfg BqBootAcpiMcfg;
typedef struct BqBootAcpiRoot BqBootAcpiRoot;
typedef struct BqBootAcpiRsdpDescriptor BqBootAcpiRsdpDescriptor;
typedef struct BqBootAcpiLedger BqBootAcpiLedger;

typedef struct BqBootKernelLayout BqBootKernelLayout;

typedef struct BqBootElfHeader BqBootElfHeader;
typedef struct BqBootElfProgramHeader BqBootElfProgramHeader;
typedef struct BqBootElfLedger BqBootElfLedger;

typedef enum   BqBootVmPageFlags BqBootVmPageFlags;
typedef struct BqBootVmPageTable BqBootVmPageTable;
typedef struct BqBootVmLedger BqBootVmLedger;

typedef enum   BqBootMemoryMapHardwareType BqBootMemoryMapHardwareType;
typedef enum   BqBootMemoryMapAcpiAttribute BqBootMemoryMapAcpiAttribute;
typedef struct BqBootMemoryMapEntry BqBootMemoryMapEntry;
typedef struct BqBootMemoryMap BqBootMemoryMap;
typedef struct BqBootMemoryMapLedger BqBootMemoryMapLedger;

typedef struct BqBootModule BqBootModule;
typedef struct BqBootInfo BqBootInfo;

BqBootStatus EFIAPI EfiMain(EfiHandle image_handle, EfiSystemTable* system_table);
void         BqBootFatalError(EfiSystemTable* system_table, const Char16* message);

BqBootStatus BqBootGopInitialize(BqBootFramebuffer* framebuffer, EfiSystemTable* system_table);

BqBootStatus BqBootAcpiFindRoot(BqBootAcpiRoot* acpi_root, EfiSystemTable* system_table);

BqBootStatus BqBootElfLoad(BqBootKernelLayout* kernel_layout, UInt64* entry_point, EfiSystemTable* system_table, EfiHandle image_handle, const Char16* kernel_path);
BqBootStatus BqBootElfLoadModules(BqBootInfo* boot_info, EfiSystemTable* system_table, EfiHandle image_handle);

BqBootStatus BqBootVmBuildPageTables(UInt64* pml4_address, EfiSystemTable* system_table, BqBootKernelLayout* kernel_layout, BqBootFramebuffer* framebuffer);
BqBootStatus BqBootVmJumpToKernel(UInt64 entry_point, UInt64 pml4_address, BqBootInfo* boot_info);

BqBootStatus BqBootMemoryMapGet(BqBootMemoryMap* memory_map, UInt64* memory_map_key, EfiSystemTable* system_table);
BqBootStatus BqBootMemoryMapTranslateDescriptors(UInt64 uefi_buf, UInt64 mmap_size, UInt64 desc_size, BqBootMemoryMapEntry* bq_entries, UInt64 max_entries, UInt32* entry_count);
BqBootStatus BqBootMemoryMapExitBootServices(BqBootMemoryMap* memory_map, EfiSystemTable* system_table, EfiHandle image_handle, UInt64 memory_map_key);

#endif
